name: Setup Workflow

on:
  workflow_call:
    inputs:
      branch: 
        description: workflow
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: echo "Deployment Completed"

      - name: Deploy application
        run: echo "Deployment Completed"
